### ISSUE TITLE
Remove android.permission.BLUETOOTH from Manifest

### ISSUE THREAD

**Issue by lakhman** [yamill/react-native-orientation#115] opened 2016-11-09 14:16 UTC
It seems this library is asking unnecessarily for Bluetooth permissions on android:

https://github.com/yamill/react-native-orientation/blob/master/android/src/main/AndroidManifest.xml#L4

Can we remove this?

As a workaround, for now, you can update the application manifest in your app with the following:

**android/app/src/main/AndroidManifest.xml**

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          xmlns:tools="http://schemas.android.com/tools"

<!-- Remove Bluetooth permissions (from react-native-orientation) -->
<uses-permission android:name="android.permission.BLUETOOTH" tools:node="remove" />

</manifest>
```

Note: You need to add the `xmlns:tools="http://schemas.android.com/tools"` else you'll get an error: 

```
[Fatal Error] :13:88: The prefix "tools" for attribute "tools:node" associated with an element type "uses-permission" is not bound.

FAILURE: Build failed with an exception.

* What went wrong:
Exception while parsing the supplied manifest file /app/android/app/src/main/AndroidManifest.xml
> The prefix "tools" for attribute "tools:node" associated with an element type "uses-permission" is not bound.
```

**Comment by colinramsay** [comment] 2017-05-23 10:25
Duplicate of #86

**Closed by colinramsay** 2017-05-23 10:25 UTC
