### ISSUE TITLE
Orientation locked to Portrait on Android Devices

### ISSUE THREAD

**Issue by aschwizzy710** [yamill/react-native-orientation#217] opened 2017-07-25 18:28 UTC
Hey - I'm installing the package directly from Github (git+https) to access the latest version and I have linked all the dependencies and configured in Android Studio as stated in the ReadMe.

When I run the app for Android, orientation is still locked in Portrait. 

Does anybody have a fix for this issue?

**Comment by andrerfneves** [comment] 2017-07-26 16:02
What are you trying to achieve @aschwizzy710? Installing the package by itself won't force your application to go landscape. You need to use the correct methods available in order to programmatically control the orientation of your application. Also, you no longer need to install from GitHub. Check README it's been updated.

**Comment by aschwizzy710** [comment] 2017-07-26 19:33
I'm attempting to see the landscape design when I rotate my phone - I know I have to programmatically control it. It is working fine on iOS. On Android, the phone does NOT rotate. @andrerfneves

**Comment by aschwizzy710** [comment] 2017-07-26 19:39
Also in the debug console - I do not see my console.logs which are supposed to fire on orientation change

**Comment by andrerfneves** [comment] 2017-07-27 15:01
@aschwizzy710 what method calls are you using? Some methods are iOS-specific. We've yet to add that to the README docs. Can you provide a gist or reproducible code that I can test?

**Comment by aschwizzy710** [comment] 2017-07-27 15:14
Regardless of the method calls I'm using, the screen should rotate in Android, correct?

I'm not using any complex logic, just switching the styles to landscape styles when the device is in Landscape orientation and vice versa in Portrait mode. 

Basically, I'm listening for orientation and using the below function to change the global orientation state in redux.

_orientationDidChange = (orientation) => {
    if (orientation === 'LANDSCAPE') {
      // do something with landscape layout
    } else {
      // do something with portrait layout
    }
  },

Then after mapping my state to the component, for example, I'd use isPortrait ? styles.portrait : styles.landscape to dynamically switch styles on orientation change.

I can't reproduce the code because it is for work. However, it is running as expected on iOS both on the device and in the simulator. When I launch the app on Android, it does not change orientation when I turn the phone and I do NOT see the console.log messages that should fire on orientation change in my debugger.

**Comment by andrerfneves** [comment] 2017-07-27 15:18
@aschwizzy710 and you're sure that you configured your native Android code from here https://github.com/yamill/react-native-orientation#configuration? It's hard to debug if I can't see any code though, I'm sure you can imagine.

**Comment by aschwizzy710** [comment] 2017-07-27 15:26
#213 might have given me a clue - I do use an orientation lock, but it is on a specific component and I unlock the orientation in componentWillUnmount() on that component which is locked.

Is that the cause for the orientation being permanently locked on Android? @andrerfneves

**Comment by andrerfneves** [comment] 2017-08-01 12:47
Closing this as the problem was resolved in another issue.

**Closed by andrerfneves** 2017-08-01 12:47 UTC
