### ISSUE TITLE
Android: Orientation Change Event not firing if Orientation is locked

### ISSUE THREAD

**Issue by facuescobar** [yamill/react-native-orientation#213] opened 2017-07-17 15:34 UTC
Hi, 

my app orientation is locked on Portrait,
on iOS I can add and receive , orientation change events even when orientation is locked.

But on Android, orientation change events are **not** firing if orientation is locked.

Can we fire orientation events event if the orientation is locked?

**Comment by aschwizzy710** [comment] 2017-07-26 19:41
+1

**Comment by andrerfneves** [comment] 2017-07-27 15:04
@aschwizzy710 @facuescobar currently the package doesn't support this. If orientation is locked, it doesn't fire on Android. It's a known caveat and PRs are highly encouraged.

**Comment by aschwizzy710** [comment] 2017-07-27 15:24
So I do use an orientation lock, but it is on a specific component and I unlock the orientation in componentWillUnmount() on that component which is locked. 

Is that the cause for the orientation being permanently locked on Android? @andrerfneves

**Comment by andrerfneves** [comment] 2017-07-27 15:26
Try `unlockAllOrientations()` as well as `lockLandscape()` in `componentWillMount` of the next view. That way it will unlock and re-lock it correctly. Maybe the `willUnmount` call is not affecting it.

**Comment by aschwizzy710** [comment] 2017-07-27 15:42
Well, I am not trying to lock it to landscape. I just want it to rotate to landscape when the phone orientation is changed and change back freely when it is changed back to portrait. I will try unlockAllOrientations in the componentWillMount of the next view.

**Comment by andrerfneves** [comment] 2017-07-27 15:45
Oh, if all you want is the ability to free up the view to move portrait/landscape, then just make sure your native Android code allows for that, and run a `unlockAllOrientations()` in `componentWillMount` of the view. As a side, in order to control my application, I explicitly `lockPortrait()` in my entry-point View, and only unlock them for views that need landscape access as well.

**Comment by aschwizzy710** [comment] 2017-07-28 14:46
Excellent - it worked! I appreciate your feedback.

**Comment by andrerfneves** [comment] 2017-07-28 14:51
@aschwizzy710 glad it worked. Closing this for now.

**Closed by andrerfneves** 2017-07-28 14:51 UTC

**Comment by aschwizzy710** [comment] 2017-08-11 15:12
Hey @andrerfneves - how do you go about calling lockPortrait()  in your entry point view (to control the app as you mentioned) if you need that view to be landscape responsive as well?

**Comment by andrerfneves** [comment] 2017-08-11 15:31
In that case just `unlockAllOrientations` at your entry point and it should behave accordingly.

**Comment by aschwizzy710** [comment] 2017-08-11 16:55
Thanks!
