### ISSUE TITLE
listener not removed after component unmount

### ISSUE THREAD

**Issue by vincentfretin** [yamill/react-native-orientation#80] opened 2016-06-19 08:39 UTC
Listener is not removed when a component is unmounted, I get a warning because a listener is called on an unmounted component.

In your code
https://github.com/yamill/react-native-orientation/blob/a7e5707e098ed9cabe714c8a5817b7b6608ebd65/index.js#L34-L46
you maintain a unneeded listeners array, but more importantly you forgot to do DeviceEventEmitter.removeListener with the good params or call the cb returned by DeviceEventEmitter.addListener with cb.remove()
please see https://github.com/inProgress-team/react-native-orientation-controller/blob/master/index.android.js#L29-L40 and https://github.com/inProgress-team/react-native-orientation-controller#removelistenercallback for a good implementation.

I now use [react-native-orientation-controller](https://github.com/inProgress-team/react-native-orientation-controller) to fix this issue.

**Comment by fackius** [comment] 2017-05-02 22:45
Hi, I am having the same issue, 

The problem is that they are using the callbacks as keys.
So when there are multiple components with the same callback function (the key), the DeviceEventEmitter listener references are overwritten on the same key.

This is the function where they add the listeners 
```javascript
  addOrientationListener(cb) {
     listeners[cb] = DeviceEventEmitter.addListener(orientationDidChangeEvent,
      (body) => {
        cb(body.orientation);
      });
  },
```

For example, with the next component

```javascript
//Other imports here
import Orientation from 'react-native-orientation';

export default class MyComponent extends Component {
    constructor() {
        super();
        this._orientationCallback = this._orientationCallback.bind(this);
    }

    componentWillMount() {
        Orientation.addOrientationListener(this._orientationCallback,);
    }

    componentWillUnmount() {
        Orientation.removeOrientationListener(this._orientationDidChange);
    }

    _orientationCallback(orientation) {
        this.setState({orientation});
    }

    render() {
        return (
            <View>
                <Text>{'Hi'}</Text>
            </View>
        );
    }
}

````

If I create three instances of this component, and I unmount both, the only listener removed will be only for the first unmounted component.
The other components will get **listeners[cb] = null** because the reference is lost.

We need a fix for this please!

**Comment by andrerfneves** [comment] 2017-07-06 19:38
Why would you create 3 instances of the same View in your application? Not entirely sure of the issue here. If you believe it stands, we accept a PR and it will be reviewed.

**Comment by facuescobar** [comment] 2017-07-13 18:24
@andrerfneves 
disregard this, I suspended this orientation feature for a while, and I took it back today.

I think there was an issue with the old structure of the component, which is now improved.

I installed the plugin again, and the listener seems to be removed correctly!
I'll let you know if I have any trouble!

thanks!

**Comment by andrerfneves** [comment] 2017-07-13 18:56
Awesome! @facuescobar glad it's working. Closing this for now.

**Closed by andrerfneves** 2017-07-13 18:56 UTC
Labels: waiting-feedback
